### ISSUE TITLE
Not working on 2018 MacBook Pro 13" - High Sierra

### ISSUE THREAD

**Issue by vcvc1010** [LumingYin/TouchBarDisabler#28] opened 2018-08-13 15:02 UTC
2018 MacBook Pro (High Sierra) - The Touch Bar remains after installing and activating TouchBarDisabler.  The input function becomes disabled and I am not able to make any selections on the Touch Bar.  But it does not disable the Touch Bar from appearing. 

Any updates that will allow TouchBarDisabler to be compatible with the 2018 MacBook Pro?  Thanks

**Comment by LumingYin** [comment] 2018-09-11 06:41
Duplicate of #27. Will investigate once I get ahold of 2018 MacBook Pro hardware. Thanks for the heads-up!

**Closed by LumingYin** 2018-09-11 06:41 UTC
